### ISSUE TITLE
How to interact with classes in modules

### ISSUE THREAD

**Issue by aitoroses** [kMeillet/bs-dynamic-import#15]
Imagine you have a module that exports a `class Rect`. How would you declare the type so that you can do `new Rect()`, I think is not currently possible to handle that specific case.

**Comment by arialpew** [comment]
**Warning :** This package is now in read-only mode, if you want to lazy load React components in a ReasonML application use "[reason-loadable](https://github.com/kMeillet/reason-loadable)".

If you want to import something else like a JSON document or JavaScript code that isn't a React component (example : Math library), take a look at "[reason-loadable](https://github.com/kMeillet/reason-loadable)" source code and tests, it can do that with some adaptation.

This package probably doesn't work anymore since BuckleScript changed object representation in JavaScript output in recent version (from array to object).
